"""empty message

Revision ID: 20a5694dcf2a
Revises: c94f6332879f
Create Date: 2020-04-04 05:34:41.099154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a5694dcf2a'
down_revision = 'c94f6332879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_timestamp'), 'chats', ['timestamp'], unique=False)
    op.create_table('professional_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True, create_constraint=True),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_chat_timestamp', table_name='chat')
    op.drop_table('chat')
    op.drop_table('status_professionals')
    op.drop_table('perfil_professionals')
    op.add_column('alerts', sa.Column('active_alert', sa.Boolean(), nullable=True, create_constraint=True))
    op.add_column('alerts', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alerts', 'professional_status', ['status_id'], ['id'])
    op.drop_column('alerts', 'alert')
    op.add_column('messages', sa.Column('message', sa.String(length=400), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'msg_sent')
    op.add_column('patients', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.drop_column('patients', 'password')
    op.drop_column('patients', 'username')
    op.add_column('professionals', sa.Column('cert_capacitaciones', sa.String(length=150), nullable=True))
    op.add_column('professionals', sa.Column('cert_profesional', sa.String(length=150), nullable=False))
    op.add_column('professionals', sa.Column('cert_spsalud', sa.String(length=150), nullable=False))
    op.add_column('professionals', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('professionals', sa.Column('rut', sa.String(length=150), nullable=False))
    op.add_column('professionals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'professionals', 'users', ['user_id'], ['id'])
    op.drop_column('professionals', 'password')
    op.drop_column('professionals', 'fullname')
    op.drop_column('professionals', 'email')
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.add_column('professionals', sa.Column('email', sa.VARCHAR(length=150), nullable=False))
    op.add_column('professionals', sa.Column('fullname', sa.VARCHAR(length=100), nullable=False))
    op.add_column('professionals', sa.Column('password', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'user_id')
    op.drop_column('professionals', 'rut')
    op.drop_column('professionals', 'name')
    op.drop_column('professionals', 'cert_spsalud')
    op.drop_column('professionals', 'cert_profesional')
    op.drop_column('professionals', 'cert_capacitaciones')
    op.add_column('patients', sa.Column('username', sa.VARCHAR(length=100), nullable=False))
    op.add_column('patients', sa.Column('password', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    op.drop_column('patients', 'name')
    op.add_column('messages', sa.Column('msg_sent', sa.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat', ['chat_id'], ['id'])
    op.drop_column('messages', 'message')
    op.add_column('alerts', sa.Column('alert', sa.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'status_id')
    op.drop_column('alerts', 'active_alert')
    op.create_table('perfil_professionals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fileCV', sa.VARCHAR(length=150), nullable=False),
    sa.Column('fileCI', sa.VARCHAR(length=150), nullable=False),
    sa.Column('fileSupSalud', sa.VARCHAR(length=150), nullable=False),
    sa.Column('fileGrade', sa.VARCHAR(length=150), nullable=False),
    sa.Column('professional_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_professionals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('available', sa.VARCHAR(length=120), nullable=False),
    sa.Column('professional_id', sa.INTEGER(), nullable=False),
    sa.Column('panic_alerts_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['panic_alerts_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_history', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_timestamp', 'chat', ['timestamp'], unique=False)
    op.drop_table('professional_status')
    op.drop_index(op.f('ix_chats_timestamp'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
